[variables]
NIXPACKS_NODE_VERSION = "22.12.0"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "HOST=0.0.0.0 node build/index.js"
